AWSTemplateFormatVersion: 2010-09-09
Resources:
  MySnsTopic:
    Type: 'AWS::SNS::Topic'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: b090899d-ca6d-493e-97c3-a63314bb2806
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: allowLambdaLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: 'arn:aws:logs:*:*:*'
        - PolicyName: allowSqs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                  - 'sqs:ChangeMessageVisibility'
        - PolicyName: allowSns
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: 'Allow - ''sns:*'''
                Resource: !GetAtt MyQueue.Arn
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e74c424a-bd31-42a1-a7b0-43e2c6c458f7
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          def handler(event,context):
            print(event)
            print(context)
            return {
              'body': 'Hello, world!',
              'headers': {
                'Content-Type': 'text/plain'
              },
              'statusCode': 200
            }          
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 60
      MemorySize: 512
      Environment:
        Variables:
          SNStopic: !Ref MySnsTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MySnsTopic.TopicName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 475b89b2-1263-4356-8bf1-5ed4c1fbf37e
  MyQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      DelaySeconds: 0
      VisibilityTimeout: 120
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 4eb438f0-73b9-4f4b-949f-b9e654b69830
Metadata:
  'AWS::CloudFormation::Designer':
    4eb438f0-73b9-4f4b-949f-b9e654b69830:
      size:
        width: 60
        height: 60
      position:
        x: 60
        'y': 90
      z: 1
      embeds: []
    e74c424a-bd31-42a1-a7b0-43e2c6c458f7:
      size:
        width: 60
        height: 60
      position:
        x: 190
        'y': 130
      z: 1
      embeds: []
    475b89b2-1263-4356-8bf1-5ed4c1fbf37e:
      size:
        width: 60
        height: 60
      position:
        x: 70
        'y': 210
      z: 1
      embeds: []
    b090899d-ca6d-493e-97c3-a63314bb2806:
      size:
        width: 60
        height: 60
      position:
        x: -70
        'y': 210
      z: 1
      embeds: []
